FROM gradle:jdk11 as builder

COPY --chown=gradle:gradle . /home/gradle/src/app

WORKDIR /home/gradle/src/app/commons
RUN gradle clean install

WORKDIR /home/gradle/src/app/events
RUN gradle clean install

WORKDIR /home/gradle/src/app
RUN gradle clean build

### ------------------------------------------- ###

FROM openjdk:11

RUN apt-get update
RUN apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt-get -y install nodejs
RUN npm install -g wait-on

ENV APP_HOME=/usr/local/app/
WORKDIR $APP_HOME

COPY ./wait-for.sh $APP_HOME
CMD chmod +x ./wait-for.sh

COPY --from=builder /home/gradle/src/app/build/libs/service-*.jar ./app.jar

# eureka
EXPOSE 8761
# config server
EXPOSE 8888
# db: postgres
EXPOSE 5432
# logstash
EXPOSE 9100
# influx
EXPOSE 8086

# app servlet
EXPOSE 8082

ENTRYPOINT bash ./wait-for.sh "${WAIT_HOSTS}" && java -jar -Dspring.profiles.active=docker app.jar
